version: '3'
services:
  app:
    image: joseph24x7/datedifference
    ports:
      - "8084:8084"
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app