server:
  port: 8888

spring:
  datasource:
    hikari:
      connection-timeout: 5000
      maximum-pool-size: 10
    url: jdbc:postgresql://localhost:5432/myuser
    username: myuser
    password: mypassword
  jpa:
      hibernate:
         ddl-auto: update
      show-sql: true
      properties:
         hibernate:
            dialect: org.hibernate.dialect.PostgreSQLDialect

management:
  endpoints:
    web:
      exposure:
        include: "*"